# Generated by Django 5.1.3 on 2024-11-28 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=100, unique=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=100)),
                ("expected_start_date", models.DateField()),
                ("expected_end_date", models.DateField()),
                (
                    "order_amount_ex_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_amount_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("status", models.CharField(max_length=50)),
                ("attachment", models.FileField(upload_to="attachments/")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
